export const ADD_SELECTED_FORM = "ADD_SELECTED_FORM";
export const DELETE_SELECTED_FORM = "DELETE_SELECTED_FORM";
export const ADD_FILLED_FORM = "ADD_FILLED_FORM";
export const TOGGLE_EDIT_FORM_MODAL = "TOGGLE_EDIT_FORM_MODAL";
export const SET_CURRENT_FORM_EDITING = "SET_CURRENT_FORM_EDITING";
export const SET_IS_AUTHENTICATED = "SET_IS_AUTHENTICATED";
export const GENERATE_INCOME_FORMS = "GENERATE_INCOME_FORMS";
